const { chromium } = require('playwright');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const page = await browser.newPage({viewport:{width:1280,height:860}});
  page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8798');
  await page.waitForLoadState('networkidle');
  assert.equal(await page.locator('.bask-od-tab.is-active').textContent(),'Overview');
  await page.getByText('Equipment proof failures',{exact:true}).waitFor();
  await page.screenshot({path:path.resolve('basidekick/task-reports/initial-ui-fixture.png')});
  console.log('Initial controls:', await page.getByRole('button').allTextContents());
  await page.getByRole('button',{name:'Histories & Trends',exact:true}).click();
  await page.getByRole('button',{name:'Add to chart',exact:true}).first().click();
  await page.getByRole('button',{name:'Add to chart',exact:true}).nth(1).click();
  await page.getByRole('textbox',{name:'Chart name',exact:true}).fill('AHU weekly review');
  await page.getByRole('combobox',{name:'Chart time range'}).selectOption('last7Days');
  await page.getByText('Analysis & export',{exact:true}).click();
  await page.getByRole('combobox',{name:'Average method'}).selectOption('time');
  await page.getByRole('spinbutton',{name:'Maximum gap in minutes'}).fill('120');
  await page.getByRole('spinbutton',{name:'Maximum gap in minutes'}).press('Tab');
  await page.getByRole('checkbox',{name:'Compare preceding period'}).check();
  await page.waitForFunction(()=>dashboard.$series.every(s=>!s.loading&&s.previous));
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('status').filter({hasText:/^Saved\.$/}).waitFor();
  await page.reload();await page.waitForLoadState('networkidle');
  await page.getByRole('button',{name:'Histories & Trends',exact:true}).click();
  await page.getByRole('button',{name:'AHU weekly review',exact:true}).click();
  assert.equal(await page.getByRole('combobox',{name:'Chart time range'}).inputValue(),'last7Days');
  assert.equal(await page.locator('.bask-od-legend-item').count(),2);
  await page.getByText('Analysis & export',{exact:true}).click();
  assert.equal(await page.getByRole('combobox',{name:'Average method'}).inputValue(),'time');
  assert.equal(await page.getByRole('spinbutton',{name:'Maximum gap in minutes'}).inputValue(),'120');
  assert.equal(await page.getByRole('checkbox',{name:'Compare preceding period'}).isChecked(),true);
  await page.waitForFunction(()=>dashboard.$series.every(s=>!s.loading&&s.previous));
  assert.equal(await page.locator('.bask-analysis').getByText('Previous mean / change:',{exact:true}).count(),2);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export loaded samples'}).click();
  const download=await downloadPromise;
  assert.equal(download.suggestedFilename(),'basidekick-history.csv');
  assert.deepEqual(await page.evaluate(()=>dashboard.$series.map(s=>s.color)),['#2563eb','#dc2626']);
  await page.getByText('Analysis & export',{exact:true}).click();
  assert.equal(await page.locator('.bask-analysis').isVisible(),false);
  assert.equal(await page.locator('.bask-analysis-summary').count(),0);
  await page.getByRole('button',{name:'▾ Saved charts',exact:true}).click();
  assert.equal(await page.getByRole('textbox',{name:'Chart name'}).isVisible(),false);
  await page.getByRole('button',{name:'▸ Saved charts',exact:true}).click();
  await page.getByRole('button',{name:'▾ Histories',exact:true}).click();
  assert.equal(await page.locator('.bask-od-history-body').isVisible(),false);
  await page.getByRole('button',{name:'▸ Histories',exact:true}).click();
  const withSidebar=await page.locator('.bask-od-chart-card').boundingBox();
  await page.getByRole('button',{name:'Sidebar',exact:true}).click();
  const withoutSidebar=await page.locator('.bask-od-chart-card').boundingBox();
  assert.ok(withoutSidebar.width>withSidebar.width+200);
  await page.getByRole('button',{name:'Sidebar',exact:true}).click();
  assert.ok((await page.locator('.bask-od-chart-wrap').boundingBox()).height>250);
  assert.equal(await page.locator('.bask-od-shell').evaluate(el=>getComputedStyle(el).borderRadius),'0px');
  await page.locator('#app').screenshot({path:path.resolve('basidekick/task-reports/dashboard-ui-fixture.png')});
  await page.getByRole('button',{name:'Name a new chart',exact:true}).click();
  await page.getByRole('textbox',{name:'Chart name',exact:true}).fill('AHU copied review');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('status').filter({hasText:/^Saved\.$/}).waitFor();
  assert.equal(await page.locator('.bask-od-saved-open').count(),2);
  await page.evaluate(()=>window.testConflict=true);
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('status').filter({hasText:'changed in another session'}).waitFor();
  await page.evaluate(()=>window.testConflict=false);
  await page.getByRole('button',{name:'Delete AHU copied review',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  assert.equal(await page.evaluate(()=>JSON.parse(sessionStorage.charts).length),2);
  await page.getByRole('button',{name:'Delete AHU copied review',exact:true}).click();
  await page.getByRole('button',{name:'Delete saved chart',exact:true}).click();
  await page.waitForFunction(()=>JSON.parse(sessionStorage.charts).length===1);
  await page.evaluate(()=>{window.testReadonly=true;dashboard.$savedCharts.refresh();});
  await page.getByRole('status').filter({hasText:'Read only.'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Save',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'Schedules',exact:true}).click();
  await page.getByRole('link',{name:'Edit full schedule & exceptions'}).waitFor();
  await page.getByRole('link',{name:'Edit full schedule & exceptions'}).click();
  assert.equal(await page.evaluate(()=>testNavigations[0]),'slot:/Schedules/Office|view:schedule:WebScheduler');
  await page.screenshot({path:path.resolve('basidekick/task-reports/schedules-ui-fixture.png')});
  await page.getByRole('combobox',{name:'Navigate to...'}).selectOption('/operations');
  assert.equal(await page.evaluate(()=>testNavigations[1]),'/operations');
  await page.setViewportSize({width:540,height:860});
  await page.getByRole('button',{name:'Histories & Trends',exact:true}).click();
  await page.getByRole('button',{name:'▾ Saved charts',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'Add to chart',exact:true}).first().isVisible(),true);
  await page.getByRole('button',{name:'▾ Histories',exact:true}).click();
  assert.ok((await page.locator('.bask-od-browser').boundingBox()).height<100);
  await page.getByRole('button',{name:'▸ Histories',exact:true}).click();
  await page.screenshot({path:path.resolve('basidekick/task-reports/narrow-ui-fixture.png')});
  const validation = await page.evaluate(()=>{
    const values=[{ord:'history:/Demo/Test',color:'#00aaff',name:'Name\nwith\ttabs'}];
    const decoded=SavedCharts.decodeSeries(SavedCharts.encodeSeries(values));
    let rejected=0;
    for(const text of ['', 'https://example.com\t#00aaff\tX','history:/Demo/X\tbad\tX','history:/Demo/X|bql:delete\t#00aaff\tX']) {
      try{SavedCharts.decodeSeries(text);}catch{rejected++;}
    }
    return {name:decoded[0].name,rejected};
  });
  assert.deepEqual(validation,{name:'Name with tabs',rejected:4});
  await page.evaluate(()=>{window.testTruncated=true;dashboard._reloadSeries();});
  await page.waitForFunction(()=>dashboard.$series.every(s=>!s.loading&&s.truncated));
  assert.equal(await page.locator('.bask-analysis strong').filter({hasText:'PARTIAL'}).count(),2);
  assert.equal(await page.locator('.bask-analysis').getByText('Unavailable: incomplete results or incompatible units',{exact:true}).count(),2);
  await page.evaluate(()=>{window.testTruncated=false;dashboard._reloadSeries();});
  await page.getByRole('button',{name:'Recent Changes',exact:true}).click();
  await page.getByRole('textbox',{name:'Audit equipment scope'}).fill('station:|slot:/Equipment/AHU1');
  await page.getByRole('button',{name:'Load recent changes'}).click();
  await page.locator('.bask-od-panel.is-active').getByText('Operator · Action invoked',{exact:true}).waitFor();
  await page.screenshot({path:path.resolve('basidekick/task-reports/recent-changes-ui-fixture.png')});
  await page.evaluate(()=>window.testAuditDenied=true);
  await page.getByRole('button',{name:'Load recent changes'}).click();
  await page.getByRole('status').filter({hasText:'Permission denied'}).waitFor();
  assert.equal(await page.locator('.bask-od-panel.is-active').getByText('Operator · Action invoked',{exact:true}).count(),0);
  await page.setViewportSize({width:1280,height:860});
  await page.locator('.showcase').screenshot({path:path.resolve('basidekick/task-reports/ui-graphics-fixture.png')});
  assert.equal(await page.locator('.bask-value-title').textContent(),'Supply Air Temperature');
  assert.equal(await page.locator('.bask-value-title').isVisible(),true);
  assert.ok((await page.locator('.bask-value-title').boundingBox()).height>=16);
  assert.equal(await page.locator('.bask-value-card').evaluate(el=>getComputedStyle(el).borderRadius),'0px');
  assert.equal(await page.locator('#inspector-launcher .bask-inspector').count(),1);
  assert.equal(await page.locator('#inspector-launcher').getByText('72.4 °F',{exact:true}).isVisible(),true);
  await page.evaluate(()=>{valueCard.properties().setValue('title','Updated title');valueCard.doChanged();});
  assert.equal(await page.locator('.bask-value-title').textContent(),'Updated title');
  await page.locator('#value-card').getByRole('button').click();
  await page.getByRole('dialog',{name:'Point inspector'}).waitFor();
  await page.screenshot({path:path.resolve('basidekick/task-reports/point-inspector-fixture.png')});
  await page.getByRole('button',{name:'Close inspector'}).click();
  assert.equal(await page.locator('#matrix tbody tr').count(),2);
  assert.equal((await page.locator('#matrix tbody tr').first().innerText()).includes('Zone 104'),true);
  await page.getByRole('button',{name:'Preview links',exact:true}).click();
  await page.getByText('Ready to add',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Apply selected',exact:true}).isDisabled(),true);
  assert.equal(await page.getByRole('checkbox',{name:'Select station:|slot:/Equipment/AHU2'}).isDisabled(),true);
  await page.getByRole('button',{name:'Select all ready'}).click();
  await page.locator('#planner').screenshot({path:path.resolve('basidekick/task-reports/link-planner-ui-fixture.png')});
  await page.getByRole('button',{name:'Apply selected',exact:true}).click();
  await page.getByText('Added',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Undo unchanged added links',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Removed 1 unchanged link'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Undo unchanged added links',exact:true}).isDisabled(),true);
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: saved analysis settings, time range/colors, comparison, CSV download, truncation, audit display/denial, planner selection/apply/undo UI, and existing saved-chart/navigation/schedule regression checks. Simulated browser fixture only.');
})().catch(e=>{console.error(e);process.exit(1)});
