define(['baja!','bajaux/Widget','jquery','nmodule/basidekick/rc/widgets/UiFoundation'],function(baja,Widget,$,UI){
  'use strict';
  function LinkPlanner(){Widget.apply(this,[{params:arguments[0],defaults:{properties:{plannerOrd:{value:'station:|slot:/LinkPlannerDemo/Planner',typeSpec:'baja:Ord'}}}}]);this.sequence=0;this.destroyed=false;this.token='';this.undoCount=0;this.busy=false;this.rows=[];}
  LinkPlanner.prototype=Object.create(Widget.prototype);LinkPlanner.prototype.constructor=LinkPlanner;
  LinkPlanner.prototype.doInitialize=function(dom){var that=this;UI.inject();this.$dom=dom.empty().addClass('bask-ui').css({fontSize:'13px',background:'var(--bask-bg)',padding:'16px',height:'100%',overflow:'auto'});this.$ord=$('<input class="bask-field" aria-label="Planner component ORD">').val(String(this.properties().getValue('plannerOrd'))).css({flex:'1',minWidth:'220px'}).on('input',function(){that.token='';that.rows=[];that.render();that.controls();});this.$preview=$('<button class="bask-btn">Preview links</button>').on('click',function(){that.call('preview',[]);});this.$apply=$('<button class="bask-btn">Apply selected</button>').on('click',function(){var ids=that.$table.find('tbody input:checked').map(function(){return this.value;}).get();if(ids.length)that.call('apply',[that.token,ids.join(',')]);});this.$select=$('<button class="bask-btn">Select all ready</button>').on('click',function(){that.$table.find('tbody input:not(:disabled)').prop('checked',true);that.controls();});this.$undo=$('<button class="bask-btn">Undo unchanged added links</button>').on('click',function(){that.call('undo',[that.token]);});this.$keep=$('<button class="bask-btn">Keep links and clear undo</button>').on('click',function(){that.call('keep',[that.token]);});this.$message=$('<div role="status" aria-live="polite"></div>').css({margin:'10px 0',fontSize:'12px',color:'var(--bask-muted)'}).text('Preview reads current wiring and does not change it.');this.$counts=$('<div></div>').css({display:'flex',gap:'7px',flexWrap:'wrap',margin:'10px 0'});this.$table=$('<table></table>').css({width:'100%',borderCollapse:'collapse',background:'var(--bask-surface)',fontSize:'12px'}).on('change','input',function(){that.controls();});this.$bar=$('<div></div>').css({position:'sticky',bottom:'-16px',display:'flex',gap:'8px',flexWrap:'wrap',alignItems:'center',padding:'12px',margin:'12px -16px -16px',background:'var(--bask-surface)',borderTop:'1px solid var(--bask-border)',boxShadow:'0 -6px 16px rgba(20,32,48,.08)'}).append(this.$select,this.$apply,$('<span></span>').css({flex:1}),this.$undo,this.$keep);dom.append($('<h2></h2>').css({fontSize:'20px',margin:'0 0 5px'}).text('Link Planner'),$('<p></p>').css({margin:'0 0 12px',color:'var(--bask-muted)'}).text('Review exact source and target properties before applying repeated equipment links.'),$('<div></div>').css({display:'flex',gap:'8px',flexWrap:'wrap'}).append(this.$ord,this.$preview),this.$message,this.$counts,$('<div></div>').css({overflow:'auto',border:'1px solid var(--bask-border)',borderRadius:'9px'}).append(this.$table),this.$bar);var $help=$('<details class="bask-planner-help"><summary>Setup and test with sample points</summary></details>').css({padding:'10px',margin:'12px 0',border:'1px solid #d9e0e7',background:'#fff'});
    $help.append($('<ol></ol>').css({paddingLeft:'20px',lineHeight:'1.7'}).append(
      $('<li></li>').text('Drag Engineering / LinkPlannerDemo from the palette to the station root. Keep its name. It contains only sample points.'),
      $('<li></li>').text('Open the Planner component’s Link Planner Widget view. Preview should show two ready links: Command.out → Result.in16.'),
      $('<li></li>').text('Select Unit1 and Apply selected. Set Unit1 / Command to Active; Unit1 / Result should follow. Unit2 stays unlinked.'),
      $('<li></li>').text('Use Undo unchanged added links. Confirm the new link is removed on Unit1’s wire sheet.')));
    $help.append($('<p></p>').text('For your own equipment, add a LinkPlanner component and set Equipment Scope to a folder of equipment. Source Path and Target Path are relative to each equipment child; Source Slot and Target Slot identify the properties to link. Preview explains any blocked rows.'));
    dom.find('h2').after($help);this.render();this.controls();return this;};
  LinkPlanner.prototype.doLoad=function(value){
    if(!this.$ord||!value||typeof value.getNavOrd!=='function')return;
    var ord=String(value.getNavOrd()).replace(/^(local:\|)+/,'').split('|view:')[0];
    if(ord.indexOf('slot:')===0)ord='station:|'+ord;
    this.$ord.val(ord);this.token='';this.rows=[];this.render();this.controls();
  };
  LinkPlanner.prototype.render=function(){var that=this,ready=this.rows.filter(function(r){return r.ready;}).length,existing=this.rows.filter(function(r){return String(r.status).indexOf('Already')===0;}).length,blocked=this.rows.length-ready-existing;this.$counts.empty();[['Ready',ready],['Blocked',blocked],['Existing',existing]].forEach(function(x){that.$counts.append($('<span></span>').css({padding:'5px 8px',border:'1px solid var(--bask-border)',borderRadius:'999px',background:'var(--bask-surface)'}).text(x[0]+' '+x[1]));});var $head=$('<tr></tr>');['','Equipment','Source','Target','Status'].forEach(function(x){$head.append($('<th></th>').css({padding:'9px',textAlign:'left',color:'var(--bask-muted)',fontSize:'10px',textTransform:'uppercase',borderBottom:'1px solid var(--bask-border)'}).text(x));});var $body=$('<tbody></tbody>');this.rows.forEach(function(row){var $check=$('<input type="checkbox">').val(row.id).attr('aria-label','Select '+(row.equipment||row.id)).prop('disabled',!row.ready),equipment=String(row.equipment||'').split('/').pop()||row.id;$body.append($('<tr></tr>').css('borderBottom','1px solid var(--bask-border)').append(td($check),td(equipment,true),td(row.source),td(row.target),td(row.status,true)));});this.$table.empty().append($('<thead></thead>').append($head),$body);};function td(value,bold){var $td=$('<td></td>').css({padding:'10px 9px',verticalAlign:'top',overflowWrap:'anywhere',fontWeight:bold?650:400});return $td.append(value&&value.jquery?value:document.createTextNode(value||''));}
  LinkPlanner.prototype.controls=function(){var selected=this.$table.find('tbody input:checked').length;this.$dom.find('button,input').prop('disabled',this.busy);this.rows.forEach(function(row,i){if(!row.ready)$(this.$table.find('tbody input')[i]).prop('disabled',true);},this);this.$apply.prop('disabled',this.busy||!this.token||!selected);this.$select.prop('disabled',this.busy||!this.token||!this.rows.some(function(r){return r.ready;}));this.$undo.add(this.$keep).prop('disabled',this.busy||!this.token||!this.undoCount);};
  LinkPlanner.prototype.call=function(method,args){var that=this,seq=++this.sequence;this.busy=true;this.controls();this.$message.text(method==='preview'?'Checking proposed links...':'Processing selected operation...');return baja.rpc({typeSpec:'basidekick:LinkPlannerRpc',method:method,args:[String(this.$ord.val()).trim()].concat(args)}).then(function(result){if(that.destroyed||seq!==that.sequence)return;var data=JSON.parse(String(result));that.token=data.token;that.undoCount=data.undoCount;that.rows=data.rows||[];that.$message.text(data.message+' '+data.undoCount+' links in the undo journal.');that.render();}).catch(function(e){if(!that.destroyed&&seq===that.sequence){that.token='';that.rows=[];that.render();that.$message.text((e.message||String(e))+' Preview again before retrying.');}}).then(function(){if(!that.destroyed&&seq===that.sequence){that.busy=false;that.controls();}});};LinkPlanner.prototype.doDestroy=function(){this.destroyed=true;this.sequence++;this.$dom.empty();};return LinkPlanner;
});
