define(['jquery','Promise','nmodule/basidekick/rc/widgets/UiFoundation'],function($,Promise,UI){
  'use strict';
  function Overview(widget){this.widget=widget;this.sequence=0;this.destroyed=false;this.loaded=false;this.$root=$('<div class="bask-od-panel"></div>').css({flexDirection:'column',padding:'12px',gap:'10px',overflow:'auto'});this.$message=$('<div class="bask-od-status" role="status"></div>');this.$grid=$('<div></div>').css({display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:'10px'});this.$root.append(this.$message,this.$grid);}
  Overview.prototype.load=function(){var that=this,seq=++this.sequence,now=Date.now(),scope=String(this.widget.properties().getValue('overviewScopeOrd')||'station:|slot:/');this.$message.text('Reading current operational exceptions...');var safe=function(p,fallback){return p.catch(function(e){fallback.error=e.message||String(e);return fallback;});};return Promise.all([
    safe(UI.rpc('basidekick:OperationsDashboardRpc','listOpenAlarms',[]),{alarms:[]}),safe(UI.rpc('basidekick:OperationsDashboardRpc','listPointHealth',[]),{points:[]}),safe(UI.rpc('basidekick:OperationsDashboardRpc','listSchedules',[]),{schedules:[]}),safe(UI.rpc('basidekick:OperationsDashboardRpc','listEquipmentProofFailures',[]),{proofs:[]}),safe(UI.rpc('basidekick:DiagnosticsRpc','recentChanges',[scope,String(now-86400000),String(now)]),{rows:[]})
  ]).then(function(all){if(that.destroyed||seq!==that.sequence)return;that.loaded=true;var alarms=all[0].alarms||[],points=all[1].points||[],schedules=all[2].schedules||[],proofs=all[3].proofs||[],changes=all[4].rows||[];var overrides=points.filter(function(p){return p.groups&&p.groups.indexOf('overridden')>=0;}),unavailable=points.filter(function(p){return p.groups&&p.groups.some(function(g){return ['fault','down','stale','disabled','null'].indexOf(g)>=0;});});that.$grid.empty();that.$grid.append(section('Open alarms',alarms.length,alarms.slice(0,5).map(function(x){return{x:x.displayName||x.sourceOrd,y:x.message||x.value};}),'health',that),section('Overrides and unavailable',overrides.length+unavailable.length,overrides.concat(unavailable).slice(0,5).map(function(x){return{x:x.displayName,y:(x.groups||[]).join(', ')+' · '+x.value};}),'health',that),section('Schedule state',schedules.length,schedules.slice(0,5).map(function(x){return{x:x.displayName,y:(x.value||'No output')+(x.nextEventMillis?' · next '+new Date(x.nextEventMillis).toLocaleString():' · no next event')};}),'schedules',that),section('Equipment proof failures',proofs.length,proofs.slice(0,5).map(function(x){return{x:x.displayName,y:x.state,ord:x.ord};}),null,that),section('Operator changes · 24h',changes.length,changes.slice(0,5).map(function(x){return{x:(x.user||'Actor unavailable')+' · '+x.operation,y:new Date(x.time).toLocaleString()+' · '+x.target};}),'changes',that));var errors=all.filter(function(x){return x.error;}).length;that.$message.text('Current station view'+(errors?' · '+errors+' sources unavailable':'')+'. Select a section to open its full workspace.');});};
  function section(title,count,rows,tab,owner){var $s=$('<section class="bask-od-section-card"></section>').css({minHeight:'160px',overflow:'hidden'}),$h=$('<button type="button"></button>').css({display:'flex',width:'100%',border:0,borderBottom:'1px solid var(--od-border)',background:'transparent',color:'inherit',padding:'12px 14px',font:'inherit',fontWeight:700,cursor:tab?'pointer':'default',textAlign:'left'}).append($('<span></span>').text(title),$('<span></span>').css({marginLeft:'auto',fontVariantNumeric:'tabular-nums'}).text(count));if(tab)$h.on('click',function(){owner.widget._activateTab(tab);});$s.append($h);if(!rows.length)$s.append($('<div></div>').css({padding:'18px 14px',color:'var(--od-muted)',fontSize:'12px'}).text('No current items.'));rows.forEach(function(row){var $row=$('<div></div>').css({padding:'8px 14px',borderBottom:'1px solid var(--od-border)',fontSize:'12px',cursor:row.ord?'pointer':'default'}).append($('<strong></strong>').css({display:'block',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}).text(row.x),$('<span></span>').css({display:'block',marginTop:'2px',color:'var(--od-muted)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}).text(row.y||''));if(row.ord)$row.attr('tabindex','0').on('click keydown',function(e){if(e.type==='click'||e.key==='Enter')UI.navigate(row.ord);});$s.append($row);});return $s;}
  Overview.prototype.destroy=function(){this.destroyed=true;this.sequence++;};return Overview;
});
