define(['baja!', 'jquery'], function (baja,$) {
  'use strict';
  function RecentChanges(widget) {
    var that=this;this.widget=widget;this.sequence=0;this.destroyed=false;this.data=[];
    this.$root=$('<div class="bask-od-panel"></div>').css({flexDirection:'column',padding:'12px',gap:'10px',overflow:'auto'});
    this.$scope=$('<input class="bask-od-input" aria-label="Audit equipment scope" placeholder="station:|slot:/Equipment/AHU1">').css({flex:'1',minWidth:'230px'}).val(String(widget.properties().getValue('overviewScopeOrd')||'station:|slot:/'));
    this.$period=$('<select class="bask-od-select" aria-label="Recent changes time range"><option value="1">Last 24 hours</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select>');
    this.$filter=$('<select class="bask-od-select" aria-label="Change operation filter"><option value="all">All operations</option><option value="property">Property changes</option><option value="action">Actions</option></select>').on('change',function(){that.render();});
    this.$load=widget._makeButton('Load recent changes').on('click',function(){that.load();});
    this.$message=$('<div class="bask-od-status" role="status" aria-live="polite"></div>').text('Audit access is required. Events are grouped by day.');this.$rows=$('<div></div>');
    this.$root.append($('<div class="bask-od-toolbar"></div>').css('flexWrap','wrap').append(this.$scope,this.$period,this.$filter,this.$load),this.$message,this.$rows);
  }
  function kind(operation){var x=String(operation||'').toLowerCase();return x.indexOf('invoke')>=0||x.indexOf('action')>=0||x.indexOf('execute')>=0?'action':'property';}
  RecentChanges.prototype.render=function(){var that=this,filter=this.$filter.val(),rows=this.data.filter(function(r){return filter==='all'||kind(r.operation)===filter;}),last='';this.$rows.empty();rows.forEach(function(row){var day=new Date(row.time).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});if(day!==last){last=day;that.$rows.append($('<h3></h3>').css({position:'sticky',top:0,zIndex:1,margin:0,padding:'10px 2px 7px',background:'var(--od-bg)',fontSize:'12px',color:'var(--od-muted)'}).text(day));}var $item=$('<div></div>').css({position:'relative',marginLeft:'7px',padding:'9px 12px 12px 20px',borderLeft:'2px solid var(--od-border)',overflowWrap:'anywhere'});$item.append($('<span></span>').css({position:'absolute',left:'-5px',top:'15px',width:'8px',height:'8px',borderRadius:'50%',background:'var(--od-accent)'}),$('<strong></strong>').text((row.user||'Actor unavailable')+' · '+row.operation),$('<div></div>').css({color:'var(--od-muted)',fontSize:'11px',marginTop:'2px'}).text(new Date(row.time).toLocaleTimeString()+' · '+row.target+' / '+row.slot),$('<div></div>').css({display:'grid',gridTemplateColumns:'minmax(0,1fr) auto minmax(0,1fr)',gap:'8px',alignItems:'center',marginTop:'7px',fontSize:'12px'}).append($('<span></span>').text(row.before==null||row.before===''?'Not recorded':row.before),$('<b aria-hidden="true">→</b>'),$('<span></span>').text(row.after==null||row.after===''?'Not recorded':row.after)));that.$rows.append($item);});if(!rows.length)this.$rows.append($('<div class="bask-od-empty"></div>').text('No events match this filter.'));};
  RecentChanges.prototype.load=function(){var that=this,seq=++this.sequence,end=Date.now(),start=end-Number(this.$period.val())*86400000;this.$rows.empty();this.$load.prop('disabled',true);this.$message.text('Reading audit history...');return baja.rpc({typeSpec:'basidekick:DiagnosticsRpc',method:'recentChanges',args:[String(this.$scope.val()).trim(),String(start),String(end)]}).then(function(result){if(that.destroyed||seq!==that.sequence)return;var data=JSON.parse(String(result));that.data=data.rows||[];that.$message.text((data.truncated?'Partial results. Narrow the range. ':'')+that.data.length+' events · newest first. '+data.note);that.render();}).catch(function(e){if(!that.destroyed&&seq===that.sequence)that.$message.text('Recent changes unavailable. '+(e.message||String(e)));}).then(function(){if(!that.destroyed&&seq===that.sequence)that.$load.prop('disabled',false);});};
  RecentChanges.prototype.destroy=function(){this.destroyed=true;this.sequence++;};return RecentChanges;
});
