define(['bajaux/Widget','jquery','nmodule/basidekick/rc/widgets/UiFoundation','nmodule/basidekick/rc/widgets/InspectorPanel'],function(Widget,$,UI,Inspector){
  'use strict';
  function ValueCard(){Widget.apply(this,[{params:arguments[0],defaults:{properties:{title:{value:'Zone Temperature',typeSpec:'baja:String'},targetOrd:{value:'station:|slot:/',typeSpec:'baja:Ord'},secondaryTargetOrd:{value:'',typeSpec:'baja:Ord'},historyOrd:{value:'',typeSpec:'baja:Ord'},auditScopeOrd:{value:'station:|slot:/',typeSpec:'baja:Ord'},detailOrd:{value:'',typeSpec:'baja:Ord'},refreshSeconds:{value:30,typeSpec:'baja:Integer'}}}}]);this.inspector=new Inspector();this.timer=0;this.sequence=0;this.destroyed=false;}
  ValueCard.prototype=Object.create(Widget.prototype);ValueCard.prototype.constructor=ValueCard;
  ValueCard.prototype.doInitialize=function(dom){
    var that=this;UI.inject();
    this.$dom=dom.empty().addClass('bask-ui').css({height:'100%',width:'100%',overflow:'hidden',background:'#fff'});
    this.$card=$('<button type="button" class="bask-value-card"></button>').css({boxSizing:'border-box',width:'100%',height:'100%',margin:0,padding:'12px 14px',border:'1px solid #d9e0e7',borderRadius:0,boxShadow:'none',textAlign:'left',font:'inherit',color:'#202832',cursor:'pointer',display:'flex',flexDirection:'column',alignItems:'stretch',background:'#fff'}).on('click',function(){that.open();});
    this.$title=$('<span class="bask-value-title"></span>').css({display:'block',flex:'0 0 auto',minHeight:'16px',lineHeight:'16px',fontSize:'12px',fontWeight:700,color:'#677383',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'});
    this.$value=$('<span class="bask-value-reading"></span>').css({display:'flex',alignItems:'center',flex:'1 1 auto',minHeight:0,fontSize:'32px',lineHeight:'38px',fontWeight:700,letterSpacing:'-.03em',overflow:'hidden'}).text('Loading...');
    this.$footer=$('<span></span>').css({display:'flex',flex:'0 0 auto',alignItems:'center',fontSize:'11px',lineHeight:'16px',color:'#677383',overflow:'hidden'});
    this.$dot=$('<span class="bask-status-dot is-muted"></span>').css({flex:'0 0 8px',marginRight:'7px'});
    this.$secondary=$('<span></span>').css({overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'});
    this.$footer.append(this.$dot,this.$secondary);this.$card.append(this.$title,this.$value,this.$footer);dom.append(this.$card);this.load();return this;
  };
  ValueCard.prototype.config=function(){return{ord:UI.property(this,'targetOrd',''),historyOrd:UI.property(this,'historyOrd',''),auditScope:UI.property(this,'auditScopeOrd',''),detailOrd:UI.property(this,'detailOrd','')};};
  ValueCard.prototype.load=function(){var that=this,seq=++this.sequence,c=this.config(),secondary=UI.property(this,'secondaryTargetOrd','');clearTimeout(this.timer);this.$title.text(UI.property(this,'title','Value')||'Value');return UI.rpc('basidekick:DiagnosticsRpc','inspectPoint',[c.ord]).then(function(point){if(that.destroyed||seq!==that.sequence)return;that.$value.text(point.value||'Unavailable');that.$dot.attr('class','bask-status-dot is-'+UI.severity(point));var label=point.groups&&point.groups.length?point.groups.join(', '):'Normal';if(secondary)return UI.rpc('basidekick:DiagnosticsRpc','inspectPoint',[secondary]).then(function(second){that.$secondary.text(label+' · '+(second.displayName||'Secondary')+': '+second.value);});that.$secondary.text(label);}).catch(function(e){if(!that.destroyed&&seq===that.sequence){that.$value.text('Unavailable');that.$secondary.text(e.message||String(e));}}).then(function(){if(!that.destroyed&&seq===that.sequence){var seconds=Math.max(5,Number(UI.property(that,'refreshSeconds','30'))||30);that.timer=setTimeout(function(){that.load();},seconds*1000);}});};
  ValueCard.prototype.open=function(){this.inspector.open(this.config());};ValueCard.prototype.doLoad=function(){if(this.$title)this.load();};ValueCard.prototype.doChanged=ValueCard.prototype.doLoad;ValueCard.prototype.doDestroy=function(){this.destroyed=true;this.sequence++;clearTimeout(this.timer);this.inspector.close();if(this.$dom)this.$dom.empty();};return ValueCard;
});
