define(['bajaux/Widget','jquery','nmodule/basidekick/rc/widgets/UiFoundation','nmodule/basidekick/rc/widgets/InspectorPanel'],function(Widget,$,UI,Inspector){
  'use strict';
  function Matrix(){Widget.apply(this,[{params:arguments[0],defaults:{properties:{title:{value:'Zone Deviation Matrix',typeSpec:'baja:String'},scopeOrd:{value:'station:|slot:/',typeSpec:'baja:Ord'},valuePath:{value:'ZoneTemp',typeSpec:'baja:String'},setpointPath:{value:'ZoneSetpoint',typeSpec:'baja:String'},refreshSeconds:{value:60,typeSpec:'baja:Integer'}}}}]);this.inspector=new Inspector();this.timer=0;this.sequence=0;this.destroyed=false;}
  Matrix.prototype=Object.create(Widget.prototype);Matrix.prototype.constructor=Matrix;
  Matrix.prototype.doInitialize=function(dom){var that=this;UI.inject();this.$dom=dom.empty().addClass('bask-ui').css({height:'100%',background:'var(--bask-bg)',padding:'12px',overflow:'auto'});this.$card=$('<section class="bask-card"></section>').css({minHeight:'100%',overflow:'hidden'});this.$head=$('<div></div>').css({padding:'14px 16px',display:'flex',alignItems:'center',gap:'10px',borderBottom:'1px solid var(--bask-border)'});this.$title=$('<strong></strong>').css({fontSize:'15px'});this.$message=$('<span></span>').css({marginLeft:'auto',fontSize:'11px',color:'var(--bask-muted)'});this.$refresh=$('<button type="button" class="bask-btn">Refresh</button>').on('click',function(){that.load();});this.$body=$('<div></div>');this.$head.append(this.$title,this.$message,this.$refresh);this.$card.append(this.$head,this.$body);dom.append(this.$card);this.load();return this;};
  Matrix.prototype.load=function(){var that=this,seq=++this.sequence,scope=UI.property(this,'scopeOrd',''),vp=UI.property(this,'valuePath',''),sp=UI.property(this,'setpointPath','');clearTimeout(this.timer);this.$title.text(UI.property(this,'title','Zone Deviation Matrix'));this.$message.text('Loading...');this.$refresh.prop('disabled',true);return UI.rpc('basidekick:DiagnosticsRpc','zoneMatrix',[scope,vp,sp]).then(function(data){if(that.destroyed||seq!==that.sequence)return;var rows=data.rows||[];rows.sort(function(a,b){if(a.deviation==null)return 1;if(b.deviation==null)return-1;return Math.abs(b.deviation)-Math.abs(a.deviation);});that.render(rows,scope);that.$message.text(rows.length+' zones · largest deviation first');}).catch(function(e){if(!that.destroyed&&seq===that.sequence){that.$body.empty().append($('<div></div>').css('padding','24px').text('Matrix unavailable. '+(e.message||String(e))));that.$message.text('Unavailable');}}).then(function(){if(!that.destroyed&&seq===that.sequence){that.$refresh.prop('disabled',false);that.timer=setTimeout(function(){that.load();},Math.max(10,Number(UI.property(that,'refreshSeconds','60'))||60)*1000);}});};
  Matrix.prototype.render=function(rows,scope){var that=this,$table=$('<table></table>').css({width:'100%',borderCollapse:'collapse',fontSize:'12px'}),$head=$('<tr></tr>');['Zone','Value','Setpoint','Deviation','Status'].forEach(function(x){$head.append($('<th></th>').css({textAlign:x==='Zone'?'left':'right',padding:'9px 12px',fontSize:'10px',textTransform:'uppercase',letterSpacing:'.06em',color:'var(--bask-muted)',borderBottom:'1px solid var(--bask-border)'}).text(x));});$table.append($('<thead></thead>').append($head));var $tbody=$('<tbody></tbody>');rows.forEach(function(row){var sev=UI.severity(row),dev=row.deviation==null?'—':(row.deviation>0?'+':'')+Number(row.deviation.toFixed(2));var $tr=$('<tr tabindex="0"></tr>').css({cursor:row.pointOrd?'pointer':'default',borderBottom:'1px solid var(--bask-border)'}).on('click keydown',function(e){if(row.pointOrd&&(e.type==='click'||e.key==='Enter'||e.key===' ')){e.preventDefault();that.inspector.open({ord:row.pointOrd,auditScope:row.equipmentOrd,detailOrd:row.equipmentOrd});}});$tr.append(cell(row.name,'left',true),cell(row.value,'right'),cell(row.setpoint,'right'),cell(dev,'right',true),$('<td></td>').css({padding:'10px 12px',textAlign:'right',whiteSpace:'nowrap'}).append($('<span class="bask-status-dot is-'+sev+'"></span>'),$('<span></span>').css('marginLeft','6px').text(row.groups&&row.groups.length?row.groups.join(', '):(row.valid?'Normal':'Unavailable'))));$tbody.append($tr);});$table.append($tbody);this.$body.empty().append($table);};
  function cell(text,align,bold){return $('<td></td>').css({padding:'10px 12px',textAlign:align,fontWeight:bold?700:400,overflowWrap:'anywhere'}).text(text==null?'—':text);}
  Matrix.prototype.doLoad=function(){if(this.$title)this.load();};Matrix.prototype.doChanged=Matrix.prototype.doLoad;Matrix.prototype.doDestroy=function(){this.destroyed=true;this.sequence++;clearTimeout(this.timer);this.inspector.close();if(this.$dom)this.$dom.empty();};return Matrix;
});
