package com.qagraphics.basidekick.ui;

import javax.baja.nre.annotations.NiagaraProperty;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.sys.Context;
import javax.baja.sys.Flags;
import javax.baja.sys.Property;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;

/**
 * Legacy alarm icon type retained so existing PX files continue to decode.
 * Alarm state no longer changes or animates the static icon.
 */
@NiagaraType
@NiagaraProperty(
  name = "alarmActive",
  type = "baja:Boolean",
  defaultValue = "false",
  flags = Flags.HIDDEN
)
public class BAlarmNavIcon
  extends BNavIcon
{
//region /*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
//@formatter:off
/*@ $com.qagraphics.basidekick.ui.BAlarmNavIcon(1)1.0$ @*/
/* Generated by hand following the Slot-o-Matic pattern; rerun slotomatic to normalize. */

  public static final Property alarmActive =
    newProperty(Flags.HIDDEN, false, null);

  public boolean getAlarmActive() { return getBoolean(alarmActive); }
  public void setAlarmActive(boolean v) { setBoolean(alarmActive, v, null); }

  @Override
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BAlarmNavIcon.class);

//@formatter:on
//endregion /*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/

  public BAlarmNavIcon()
  {
    setIconType(BIconType.alarm);
  }

  @Override
  public void changed(Property property, Context context)
  {
    super.changed(property, context);
    if (property == alarmActive)
    {
      requestImageRefresh();
    }
  }

}
