package com.qagraphics.basidekick.ui;

import javax.baja.nre.annotations.NiagaraEnum;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.nre.annotations.Range;
import javax.baja.sys.BFrozenEnum;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;

/**
 * Neutral icon appearance for light or dark mode.
 */
@NiagaraType
@NiagaraEnum(range = {
  @Range("light"),
  @Range("dark")
})
public final class BIconMode
  extends BFrozenEnum
{
//region /*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
//@formatter:off
/*@ $com.qagraphics.basidekick.ui.BIconMode(1)1.0$ @*/
/* Generated by hand following the Slot-o-Matic pattern; rerun slotomatic to normalize. */

  public static final int LIGHT = 0;
  public static final int DARK = 1;

  public static final BIconMode light = new BIconMode(LIGHT);
  public static final BIconMode dark = new BIconMode(DARK);

  public static BIconMode make(int ordinal)
  {
    return (BIconMode)light.getRange().get(ordinal, false);
  }

  public static BIconMode make(String tag)
  {
    return (BIconMode)light.getRange().get(tag);
  }

  private BIconMode(int ordinal)
  {
    super(ordinal);
  }

  public static final BIconMode DEFAULT = light;

  @Override
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BIconMode.class);

//@formatter:on
//endregion /*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/
}
