package com.qagraphics.basidekick.ui;

import javax.baja.nre.annotations.NiagaraEnum;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.nre.annotations.Range;
import javax.baja.sys.BFrozenEnum;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;

/**
 * Icon subjects included in the BAS icon source document.
 */
@NiagaraType
@NiagaraEnum(range = {
  @Range("siteCampus"),
  @Range("home"),
  @Range("alarm"),
  @Range("schedules"),
  @Range("trends"),
  @Range("users"),
  @Range("dashboard"),
  @Range("weather"),
  @Range("airSystems"),
  @Range("waterSystems"),
  @Range("floorPlans"),
  @Range("reports"),
  @Range("miscellaneous")
})
public final class BIconType
  extends BFrozenEnum
{
//region /*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
//@formatter:off
/*@ $com.qagraphics.basidekick.ui.BIconType(1)1.0$ @*/
/* Generated by hand following the Slot-o-Matic pattern; rerun slotomatic to normalize. */

  public static final int SITE_CAMPUS = 0;
  public static final int HOME = 1;
  public static final int ALARM = 2;
  public static final int SCHEDULES = 3;
  public static final int TRENDS = 4;
  public static final int USERS = 5;
  public static final int DASHBOARD = 6;
  public static final int WEATHER = 7;
  public static final int AIR_SYSTEMS = 8;
  public static final int WATER_SYSTEMS = 9;
  public static final int FLOOR_PLANS = 10;
  public static final int REPORTS = 11;
  public static final int MISCELLANEOUS = 12;

  public static final BIconType siteCampus = new BIconType(SITE_CAMPUS);
  public static final BIconType home = new BIconType(HOME);
  public static final BIconType alarm = new BIconType(ALARM);
  public static final BIconType schedules = new BIconType(SCHEDULES);
  public static final BIconType trends = new BIconType(TRENDS);
  public static final BIconType users = new BIconType(USERS);
  public static final BIconType dashboard = new BIconType(DASHBOARD);
  public static final BIconType weather = new BIconType(WEATHER);
  public static final BIconType airSystems = new BIconType(AIR_SYSTEMS);
  public static final BIconType waterSystems = new BIconType(WATER_SYSTEMS);
  public static final BIconType floorPlans = new BIconType(FLOOR_PLANS);
  public static final BIconType reports = new BIconType(REPORTS);
  public static final BIconType miscellaneous = new BIconType(MISCELLANEOUS);

  public static BIconType make(int ordinal)
  {
    return (BIconType)siteCampus.getRange().get(ordinal, false);
  }

  public static BIconType make(String tag)
  {
    return (BIconType)siteCampus.getRange().get(tag);
  }

  private BIconType(int ordinal)
  {
    super(ordinal);
  }

  public static final BIconType DEFAULT = siteCampus;

  @Override
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BIconType.class);

//@formatter:on
//endregion /*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/
}
