package com.qagraphics.basidekick.ui;

import javax.baja.nre.annotations.NiagaraEnum;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.nre.annotations.Range;
import javax.baja.sys.BFrozenEnum;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;

/**
 * Visual style supplied by the BAS icon source document.
 */
@NiagaraType
@NiagaraEnum(range = {
  @Range("illustrated"),
  @Range("duotone"),
  @Range("softLine"),
  @Range("solidGlyph"),
  @Range("schematic")
})
public final class BIconStyle
  extends BFrozenEnum
{
//region /*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
//@formatter:off
/*@ $com.qagraphics.basidekick.ui.BIconStyle(1)1.0$ @*/
/* Generated by hand following the Slot-o-Matic pattern; rerun slotomatic to normalize. */

  public static final int ILLUSTRATED = 0;
  public static final int DUOTONE = 1;
  public static final int SOFT_LINE = 2;
  public static final int SOLID_GLYPH = 3;
  public static final int SCHEMATIC = 4;

  public static final BIconStyle illustrated = new BIconStyle(ILLUSTRATED);
  public static final BIconStyle duotone = new BIconStyle(DUOTONE);
  public static final BIconStyle softLine = new BIconStyle(SOFT_LINE);
  public static final BIconStyle solidGlyph = new BIconStyle(SOLID_GLYPH);
  public static final BIconStyle schematic = new BIconStyle(SCHEMATIC);

  public static BIconStyle make(int ordinal)
  {
    return (BIconStyle)illustrated.getRange().get(ordinal, false);
  }

  public static BIconStyle make(String tag)
  {
    return (BIconStyle)illustrated.getRange().get(tag);
  }

  private BIconStyle(int ordinal)
  {
    super(ordinal);
  }

  public static final BIconStyle DEFAULT = illustrated;

  @Override
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BIconStyle.class);

//@formatter:on
//endregion /*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/
}
