package com.qagraphics.basidekick.ui;

import javax.baja.gx.BImage;
import javax.baja.gx.Graphics;
import javax.baja.nre.annotations.NiagaraProperty;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.sys.Context;
import javax.baja.sys.Flags;
import javax.baja.sys.Property;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;
import javax.baja.ui.BPicture;
import javax.baja.ui.BWidget;

/**
 * A native Niagara Picture backed by one of the bundled static SVG icons.
 *
 * The widget deliberately subclasses {@link BPicture}, so Niagara's normal
 * Picture renderer, scale property, and ValueBinding hyperlink behavior remain
 * in use without requiring UxMedia.
 */
@NiagaraType
@NiagaraProperty(
  name = "iconType",
  type = "BIconType",
  defaultValue = "BIconType.home",
  flags = Flags.HIDDEN
)
@NiagaraProperty(
  name = "style",
  type = "BIconStyle",
  defaultValue = "BIconStyle.illustrated",
  flags = Flags.HIDDEN
)
public class BNavIcon
  extends BPicture
{
//region /*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
//@formatter:off
/*@ $com.qagraphics.basidekick.ui.BNavIcon(1)1.0$ @*/
/* Generated by hand following the Slot-o-Matic pattern; rerun slotomatic to normalize. */

  public static final Property iconType =
    newProperty(Flags.HIDDEN, BIconType.home, null);

  public BIconType getIconType() { return (BIconType)get(iconType); }
  public void setIconType(BIconType v) { set(iconType, v, null); }

  public static final Property style =
    newProperty(Flags.HIDDEN, BIconStyle.illustrated, null);

  public BIconStyle getStyle() { return (BIconStyle)get(style); }
  public void setStyle(BIconStyle v) { set(style, v, null); }

  @Override
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BNavIcon.class);

//@formatter:on
//endregion /*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/

  @Override
  public void computePreferredSize()
  {
    setPreferredSize(40, 40);
  }

  @Override
  public void changed(Property property, Context context)
  {
    super.changed(property, context);
    if (property == iconType || property == style)
    {
      requestImageRefresh();
    }
  }

  protected final void requestImageRefresh()
  {
    imageDirty = true;
    repaint();
  }

  @Override
  public void doLayout(BWidget[] children)
  {
    ensureImage();
    super.doLayout(children);
  }

  @Override
  public void paint(Graphics graphics)
  {
    ensureImage();
    super.paint(graphics);
  }

  protected String resourceVariantSuffix()
  {
    return "";
  }

  private void ensureImage()
  {
    if (!imageDirty || refreshing) return;

    refreshing = true;
    imageDirty = false;
    try
    {
      setImage(BImage.NULL);
      setImage(BImage.make(imageUri()));
    }
    finally
    {
      refreshing = false;
    }
  }

  private String imageUri()
  {
    return "module://basidekick" + resourcePath();
  }

  private String resourcePath()
  {
    String icon = iconFileName(getIconType());
    String styleName = styleFileName(getStyle());
    return "/Icons/" + icon + "/" + icon + "-" + styleName +
      resourceVariantSuffix() + ".svg";
  }

  static String iconFileName(BIconType iconType)
  {
    if (iconType == BIconType.siteCampus) return "SiteCampus";
    if (iconType == BIconType.alarm) return "Alarm";
    if (iconType == BIconType.schedules) return "Schedules";
    if (iconType == BIconType.trends) return "Trends";
    if (iconType == BIconType.users) return "Users";
    if (iconType == BIconType.dashboard) return "Dashboard";
    if (iconType == BIconType.weather) return "Weather";
    if (iconType == BIconType.airSystems) return "AirSystems";
    if (iconType == BIconType.waterSystems) return "WaterSystems";
    if (iconType == BIconType.floorPlans) return "FloorPlans";
    if (iconType == BIconType.reports) return "Reports";
    if (iconType == BIconType.miscellaneous) return "Miscellaneous";
    return "Home";
  }

  static String styleFileName(BIconStyle iconStyle)
  {
    if (iconStyle == BIconStyle.duotone) return "Duotone";
    if (iconStyle == BIconStyle.softLine) return "SoftLine";
    if (iconStyle == BIconStyle.solidGlyph) return "SolidGlyph";
    if (iconStyle == BIconStyle.schematic) return "Schematic";
    return "Illustrated";
  }

  private boolean imageDirty = true;
  private boolean refreshing;
}
