package com.qagraphics.basidekick.ui;

import javax.baja.nre.annotations.NiagaraProperty;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.sys.Context;
import javax.baja.sys.Flags;
import javax.baja.sys.Property;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;

/**
 * Static neutral navigation icon with light and dark modes.
 */
@NiagaraType
@NiagaraProperty(
  name = "mode",
  type = "BIconMode",
  defaultValue = "BIconMode.light",
  flags = Flags.SUMMARY
)
public class BNeutralNavIcon
  extends BNavIcon
{
//region /*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
//@formatter:off
/*@ $com.qagraphics.basidekick.ui.BNeutralNavIcon(1)1.0$ @*/
/* Generated by hand following the Slot-o-Matic pattern; rerun slotomatic to normalize. */

  public static final Property mode =
    newProperty(Flags.SUMMARY, BIconMode.light, null);

  public BIconMode getMode() { return (BIconMode)get(mode); }
  public void setMode(BIconMode v) { set(mode, v, null); }

  @Override
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BNeutralNavIcon.class);

//@formatter:on
//endregion /*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/

  @Override
  public void changed(Property property, Context context)
  {
    super.changed(property, context);
    if (property == mode) requestImageRefresh();
  }

  @Override
  protected String resourceVariantSuffix()
  {
    if (getStyle() == BIconStyle.duotone) return "";
    return getMode() == BIconMode.dark ? "-Dark" : "";
  }
}
